title: "Khang"
description: "Test"
baseurl: ""
url: "https://kuhekin.github.io/mycv"

theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
